### ISSUE TITLE
Remove trial requests from website

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/mavc-theme#14]
iLab will send us a list of requests which are classified as 'trial' not 'real' requests so that we can remove them from the site.

**Comment by garethrees** [comment]
They should be able to do this through the admin interface:

![screen shot 2015-08-12 at 11 36 28](https://cloud.githubusercontent.com/assets/282788/9222022/634833ae-40e6-11e5-9f6f-84056a79c892.png)

**Comment by JenMysoc** [comment]
I've tried that and thought I'd done them all. I can't get rid of the authorities though.

**Comment by garethrees** [comment]
Ah okay this ticket doesn't say anything about authorities. I thought that was covered by https://github.com/mysociety/mavc-theme/issues/12?

**Comment by JenMysoc** [comment]
It is, sorry I didn't mean to confuse but I've done this i believe.

**Comment by garethrees** [comment]
Awesome! Will close this one \o/
