### ISSUE TITLE
Add new pages to the site

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/mavc-theme#16]
Add content pages about:
- the FOI law in general and the rights of citizens
- the role of the IIC and how citizens can use it
- a description of the OGP process and the role of the site as part of the OGP commitments
- partners for the site

The content for these pages will be provided by Carter and the team.

**Comment by garethrees** [comment]
http://daringfireball.net/projects/markdown/syntax

**Comment by Gemmamysoc** [comment]
Email from Carter on 2 Sept about new page titles:-
- [x] FOI Awareness (For citizens while on the site, to have access to the Awareness materials)
- [x] ~~File a complaint (To all citizens to file Complaints on the site immediately. This should send an email to the Independent Information Commission)~~ (#28)
- [x] Partners (For all partners promoting and monitoring the FIOA for compliance like the CSOs) 
- [x] The IIC (This page will present contents about the IIC as the governing body of FOIA)

Carter does not currently have all the contents for these pages, but if we can give him the permission to edit these pages and add contents, he could start to populate them as he receives such contents. Is this possible?

**Comment by garethrees** [comment]
> Carter does not currently have all the contents for these pages, but if we can give him the permission to edit these pages and add contents, he could start to populate them as he receives such contents. Is this possible?

The pages can only be edited through GitHub – he'll have to fork this repository and submit pull requests. Is he comfortable editing raw html?

**Comment by Gemmamysoc** [comment]
Carter says he's comfortable editing raw html but it might be a bit too much work for him on top of everything else he's doing. What he'll do is ensure he collects the contents as soon as possible to share before the end of current sprint.

**Comment by garethrees** [comment]
[FOI Awareness](http://infolib.org.lr/help/foi_awareness), [Partners](http://infolib.org.lr/help/partners) and [The IIC](http://infolib.org.lr/help/the_iic) have been added.

~~Haven't (AFAIK) had content for "File a complaint". At the moment we're using the default [UK version](http://infolib.org.lr/help/unhappy).~~ #28

**Comment by garethrees** [comment]
We've also been asked to add them to the menu bar (in #18). They've been added to the help sidebar, but not the main nav.

**Comment by garethrees** [comment]
The remaining work here is being handled in #21
