### ISSUE TITLE
Change site domain name to infolib.org.lr

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/mavc-theme#3]
Site domain needs to be bought. @paullenz and @JenMySoc need to arrange for this to happen

**Comment by JenMysoc** [comment]
@paullenz has confirmed mySociety will register the domain and transfer ownership once it has been decided who will be administrating the website.

**Comment by Flupsy** [comment]
Am looking into this.

**Comment by Flupsy** [comment]
I don't think a non-Liberian entity can register a .lr domain:

Registrations must be from organizations with a real presence in the country and with a demonstrable intent to use the domain name on a regular basis on the internet. I.e. vanity, placemark, ... name registration is not appropriate. For trademark registration, see the trademark office. (from http://psg.com/dns/lr/)

**Comment by Flupsy** [comment]
Domain is now registered and we're serving the DNS records.

**Comment by garethrees** [comment]
Done http://infolib.org.lr/
