### ISSUE TITLE
Email issue with emails going to wrong place

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/mavc-theme#33]
Is there an override on to send all messages to a specific address for infoLib?

Some new email addresses have been added for PIOs with their new devices but infoLib is only sending to the iLab tablet email addresses.

**Comment by garethrees** [comment]
> Is there an override on to send all messages to a specific address for infoLib?

Yes, this was requested for the training session.

**Comment by JenMysoc** [comment]
Aha! I thought this was the case, what needs to be done to change this?

**Comment by garethrees** [comment]
The override is all or nothing, so if we take it off requests will go to whatever email address is listed for the public authority.

If they only want to send to _some_ public authorities, we could remove the override and Carter could set the request address to his team address for the ones they _don't_ want requests to go to yet. If he does this, I'd suggest also adding a comment in the "Notes" field to say that the requests are going to him, and that the real public authority isn't accepting requests yet.

**Comment by JenMysoc** [comment]
Ok I'll ask him what he prefers, thanks!
