### ISSUE TITLE
Change header image to Liberian Flag

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/mavc-theme#4]
This will need some discussion with Carter et al in July to get the exact idea eg: will the flag cover the whole header or will it be an image in the header and the rest is neutrally coloured

![liberia flag](https://cloud.githubusercontent.com/assets/739624/8797904/94b5d86c-2f96-11e5-8b3b-672108f230be.gif)

**Comment by JenMysoc** [comment]
Carter said "the flag is expected to cover the entire header, but fading out at the right end."

**Comment by wrightmartin** [comment]
I'm looking at this now. 

It's going to be tricky to get the flag to cover the whole header for two reasons:
- The readability of any text in the header will be negatively impacted. I'll have to darken it, or do something to the overlaying text
- The image is only 543 pixels wide. The header can be anything from 0 to 2560 pixels, it will look very rough at anything above 543 pixels.

**Comment by JenMysoc** [comment]
I will ask Paul to check with Carter but is it possible to edit the image (I believe that had been Zarino's original plan: to remake the flag image to something of a higher image quality) and have it: 
![screen shot 2015-07-30 at 14 33 11](https://cloud.githubusercontent.com/assets/4170351/8984213/1867d6b4-36c8-11e5-90d3-72560c686420.png)
on the dark blue area from the left hand edge fading out just after where the name of the platform lies?

We need to change the name of the site anyway I am assuming as I don't think we want it to be called Alaveteli since that's the Platform name.

**Comment by wrightmartin** [comment]
Something like this?

![liberia-header](https://cloud.githubusercontent.com/assets/2292925/8984424/720a2c8e-36c9-11e5-92d2-af8a1e75fa98.jpg)

**Comment by paullenz** [comment]
Carter says that would be cool - thanks!

**Comment by paullenz** [comment]
Ooo - more feedback - would it be possible to extend the flag fade to the
right any further?  Not vital for the flag to retain original proportions

**Comment by wrightmartin** [comment]
@paullenz at that point it starts to interfere with the text of the logged-in menu, I'll see what I can do

**Comment by wrightmartin** [comment]
PR here https://github.com/mysociety/mavc-theme/pull/9

**Comment by garethrees** [comment]
Fixed in #9
