### ISSUE TITLE
Front-page looks clunky on tablets

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/mavc-theme#45]
On my Nexus the front page looks super clunky and since the PIOs are mainly accessing from tablets this should probably be sorted out. 
![screenshot_20160330-224429](https://cloud.githubusercontent.com/assets/4170351/14158765/e848806a-f6c9-11e5-993c-4ccf40cda960.png)

**Comment by zarino** [comment]
Minimal fix here: https://github.com/mysociety/mavc-theme/pull/46

**Comment by JenMysoc** [comment]
Thanks guys!
