### ISSUE TITLE
[ERROR] request#show (ActionView::Template::Error) "undefined method `id' for nil:NilClass"

### ISSUE THREAD

**Issue by garethrees** [mysociety/mavc-theme#55]
```
An ActionView::Template::Error occurred in request#show:

undefined method `id' for nil:NilClass
app/views/request/_outgoing_correspondence.html.erb:1:in `_app_views_request__outgoing_correspondence_html_erb__3536311074862054513_47029659860560'


-------------------------------
Request:
-------------------------------

* URL : https://infolib.org.lr/request/testing_account_of_mia
* HTTP Method: GET
* Parameters : {"controller"=>"request", "action"=>"show", "url_title"=>"testing_account_of_mia"}
* Timestamp : 2020-08-20 15:26:59 +0000
* Rails root : /data/vhost/liberia.alaveteli.org/alaveteli-2020-08-20T08-49-29

-------------------------------
Backtrace:
-------------------------------

app/views/request/_outgoing_correspondence.html.erb:1:in `_app_views_request__outgoing_correspondence_html_erb__3536311074862054513_47029659860560'
app/views/request/events/_sent.html.erb:1:in `_app_views_request_events__sent_html_erb___2855710859112121606_47029659689000'
app/views/request/_correspondence.html.erb:5:in `_app_views_request__correspondence_html_erb___1029444482278918074_47029659619860'
app/views/request/show.html.erb:40:in `block in _app_views_request_show_html_erb___1464389208891537884_47029652949640'
app/views/request/show.html.erb:38:in `_app_views_request_show_html_erb___1464389208891537884_47029652949640'
app/controllers/request_controller.rb:125:in `block (3 levels) in show'
app/controllers/request_controller.rb:124:in `block in show'
lib/alaveteli_localization.rb:46:in `with_locale'
app/controllers/request_controller.rb:75:in `show'
app/controllers/application_controller.rb:116:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by garethrees** [comment]
Looks like this is a request without an initial outgoing message:

https://github.com/mysociety/alaveteli/blob/0.38.1.0/app/views/request/_outgoing_correspondence.html.erb#L1

Perhaps it failed to send during the upgrade?

**Comment by garethrees** [comment]
The request was created at `2 December 2015 11:13:05 (over 4 years ago)`, and on `7 January 2016 15:41:08 (over 4 years ago)` the outgoing message and subsequent outgoing message was destroyed.

There's a new `InfoRequestEvent` `Sent` event created at `20 August 2020 08:30:12 (12 days ago)`.

Given this was a test request, I've just deleted it entirely.

**Comment by garethrees** [comment]
Same situation for https://infolib.org.lr/request/testing_account_of_mia – created over 4 years ago; incoming/outgoing messages destroyed soon after; new `Sent` event 12 days ago. Destroyed the request.

**Comment by garethrees** [comment]
Also destroyed these testing requests – all identical pattern:

* https://infolib.org.lr/request/testing_gsa_account
* https://infolib.org.lr/request/testing_micat_account
* https://infolib.org.lr/request/testing_mopt_account
* https://infolib.org.lr/request/testing_mod_account
* https://infolib.org.lr/request/testing_mopw_account

**Comment by gbp** [comment]
Ah sorry I created those new `InfoRequestEvent` when upgrading so the database would be able to migrate
