### ISSUE TITLE
Add IIC Logo and Liberian Seal to bottom right hand of footer

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/mavc-theme#6]
@jenmysoc needs to get image files from Carter

**Comment by paullenz** [comment]
Have these been requested?

**Comment by JenMysoc** [comment]
Yes twice.

**Comment by JenMysoc** [comment]
![logosmall](https://cloud.githubusercontent.com/assets/4170351/9084563/09ebb87c-3b6d-11e5-8e8b-8415b6279eb9.png)

I also have an .svg version if it's needed :) 

![iic logo](https://cloud.githubusercontent.com/assets/4170351/9084602/5c7223d8-3b6d-11e5-9c87-5543d675dcda.png)

**Comment by garethrees** [comment]
Fixed in https://github.com/mysociety/mavc-theme/pull/13 and deployed
